services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: taxi_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - de_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d taxi_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  pipeline:
    build: .
    env_file:
      - .env
    environment:
      DB_HOST: postgres
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - de_network

  metabase:
    image: metabase/metabase:latest
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: h2
      MB_DB_FILE: /metabase-data/metabase.db
    volumes:
      - metabase_data:/metabase-data
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - de_network

volumes:
  postgres_data:
  metabase_data:

networks:
  de_network:
